version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.31
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    container_name: bookstack
    image: solidnerd/bookstack:0.30.4
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads

  bookstack_proxy:
    container_name: bookstack_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - bookstack
      - mysql
    environment:
      HOST: localhost
    ports:
      - "80:80"
    volumes:
      - ./bookstack_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bookstack_proxy/certificates:/etc/nginx/certificates
    command: [nginx, '-g', 'daemon off;']

volumes:
 mysql-data:
 uploads:
 storage-uploads:
